name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün otomatik çalıştırır

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git deposunu klonla
        uses: actions/checkout@v3

      - name: Snake Animasyonunu Üret
        uses: Platane/snk@v3
        with:
          github_user_name: yaseminozhan
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Çıktıyı Push Et
        run: |
          mkdir -p dist
          mv github-contribution-grid-snake.svg dist/
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Yılan animasyonu güncellendi"
          git push
